### ISSUE TITLE
v12 checklist

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/Ludus_ProtoShield_Wireless#5]
(1) GND Test-point should use a gnd symbol

(2) None of the VCC or VIN sugnals use a "VCC Symbol" (up to you as to whether or not you want to fix this, personally it doesn't seem worth the time, but it's worth mentioning as it is in the checklist)

(3) Currently the assembly is only sku'ed as a SUB (pd sku), but I believe this will also be sold on storefront, in these cases we give the assembly a SF sku and build under that, then we allocate a certain quantity to production upon receiving the batch. At that point it gets transferred to the pd sku.  I'm not sure how we are handling this assembly in particular, but it seemed worth mention. 

(4) Needed edits to BOM: +1  DIO-821, -1 DIO-8575, +2 RES-824, +1 RES-77856, -1 RES-11150, +1 TRANS-8049, +1 TRANS-11308

**Comment by ShawnHymel** [comment]
1) Added.
2) Most of the power symbols are actually FUSED_xV, so I'll leave them as flags for now.
3) Looks like it's listed as DEV-14285 for storefront, so we should be good.
4) Done.
