### ISSUE TITLE
v14 double-check for REDS

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/Ludus_ProtoShield_Wireless#6]
1) Are the part libraries consistent with eagle github repo? [NO]
comment: RES and LED still have silk under them. needs library update

2) Have you verified that the BOM in Sparkle is accurate (also checking for PROD_ID, NAME, VALUE, PREFIX)? [NO]
comment: J2 needs PROD_ID (SMD 4 pin RA header for I2C port)

**Comment by ShawnHymel** [comment]
Both fixed.
